MWI_dir = "c:\winnt\installer\mwi"
MWI_share = "c$\winnt\installer\mwi"
INI_Destination_Loc = "Wrapper\INI"
share_root = r"\\frkfnabk1\support\software"
psexec_loc = "f:\pstools\PsExec"
Wrapper = "c:\winnt\installer\mwi\Wrapper\MSIWrapper.exe"
